### ISSUE TITLE
换成mipi接口的AN5641（单个ov5640）可行吗

### ISSUE THREAD

**Issue by DragMou1204** [huanggeli/yolov3tiny-ZYNQ7000#1]

**Comment by DragMou1204** [comment]
是输出axi4-stream就可以了吧

**Comment by huanggeli** [comment]
是的，把ov5640 IP核替换一下就行，RGB565-RGB888的IP根据实际情况决定是否保留

**Comment by DragMou1204** [comment]
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/119485272/34908ccb-d893-46fa-8536-b81b7c1fcae9)
我想要移植你的项目 我的板子型号为zu5ev，你的hls生成的ip我这无法适用，也检测不到你的hls_ip

**Comment by huanggeli** [comment]
ip文件夹补传了HLS的源码，实际上本项目是参考 https://github.com/adamgallas/fpga_accelerator_yolov3tiny/tree/main/

本项目针对zynq7000做了针对性的优化，若不是zynq7000可以直接参考源项目













在 2023-12-05 15:51:40，"DragMou1204" ***@***.***> 写道：

image.png (view on web)
我想要移植你的项目 我的板子型号为zu5ev，你的hls生成的ip我这无法适用，也检测不到你的hls_ip

**Comment by DragMou1204** [comment]
感谢，我看到过这个源项目，也进行了移植，但没有成功，显示器没有显示

**Comment by huanggeli** [comment]
卷积IP和DMA可以不用动，剩下图像采集和显示的回路建议先根据开发板型号自己调通



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月05日 16:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] 换成mipi接口的AN5641（单个ov5640）可行吗 (Issue #1) |

感谢，我看到过这个源项目，也进行了移植，但没有成功，显示器没有显示

**Comment by DragMou1204** [comment]
ok

**Comment by DragMou1204** [comment]
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/119485272/9e885414-4d67-4bad-8d22-722c8e39e866)
请问，我建立的vitis工程，刚刚导入xsa文件生成platform，该platform就报错，请问你知道原因吗

**Comment by DragMou1204** [comment]
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/119485272/2d5dbbd9-2326-47a5-ac90-f0b0632458f6)
platform不报错了，但是build完就显示 out of date ，然后build应用时不产生fsbl.elf,Debug/sd_card文件夹下也不生成boot.bin,这是什么原因呢

**Comment by huanggeli** [comment]
本项目使用jtag模式进行过验证（hardware debugger），您的问题可能是vitis在修改platform后没能适配的问题，可以考虑把源码复制出来重新创建application，若仍未解决问题则有以下思路：
1、若您的开发板不是zynq7000：考虑是否根据开发型号在vivado的开发阶段替换了PS的核，PS核是否配置正确，编译时是否选择了正确的芯片型号
2、查询开发板的对应手册。

**Comment by DragMou1204** [comment]
已经解决了，可以运行application了，但是没显示，程序卡在了Inference的 wait ap_done了，正在找原因

**Comment by huanggeli** [comment]
好的，wait apdone是通过中断传入的，可以重点检查外部IP复位信号是否设置正确，中断绑定是否正确等问题，考虑到这个issue的主题已经解决，我先关掉本issue。有其他问题可以开新的issue提交

**Comment by DragMou1204** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月07日 21:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] 换成mipi接口的AN5641（单个ov5640）可行吗 (Issue #1) |

好的，wait apdone是通过中断传入的，可以重点检查外部IP复位信号是否设置正确，中断绑定是否正确等问题，考虑到这个issue的主题已经解决，我先关掉本issue。有其他问题可以开新的issue提交

**Comment by DragMou1204** [comment]
感谢您的解答



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月07日 21:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] 换成mipi接口的AN5641（单个ov5640）可行吗 (Issue #1) |

好的，wait apdone是通过中断传入的，可以重点检查外部IP复位信号是否设置正确，中断绑定是否正确等问题，考虑到这个issue的主题已经解决，我先关掉本issue。有其他问题可以开新的issue提交
