### ISSUE TITLE
多种物体检测识别

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#10]
您好，我看了目前的代码，好像是只支持一种物体。请问支持检测几种物体吗？
比如我训练的是检测苹果和香蕉的权重，能够检测到苹果和香蕉吗

**Comment by huanggeli** [comment]
8种物体以内，但是NMS只筛选了概率值最大的结果，所以苹果香蕉同时出现时，只会显示一种结果（prob最高）。要想同时检测多种物体需要修改硬件的IP(增加一个画框IP)，软件修改NMS的代码。
