### ISSUE TITLE
关于量化权重文件的生成

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#11]
您好，我看了原工程的python代码。做了这样的调用

```python
img_path='gao_mask.jpg'
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # 将BGR转换为RGB
from torchvision import transforms

# 预处理图像
transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((640, 640)),  # 假设模型输入尺寸为640x640
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])  # 标准化
])
img_tensor = transform(img).unsqueeze(0)  # 添加批次维度

float_model,dataloader_iter=load_model_data('face_mask.yaml','yolov3tiny_facemask.pt',416,False)
generate_quant_model(float_model,dataloader_iter,'yolov3tiny_facemask_quant.pth')
quant_model=load_quant_model('yolov3tiny_facemask.pt','yolov3tiny_facemask_quant.pth')
quant_model_evaluate_show(img_tensor,quant_model)
yolov3tiny_infer_para_gen(quant_model,32,'F')
```
目录如下
 python_prj
  |── images
  |── labels(代码中好像没遇到)
 └── yolov3tiny_quant.py

最后在quant_model_evaluate_show函数报错，这个函数应该是看下分割的权重能否正确检测。
Input shape must be (N, C, H, W)!
File "D:\yolo_work\fpga_accelerator_yolov3tiny\python_prj\models\common.py", line 45, in fuseforward
return self.act(self.conv(x))
File "D:\yolo_work\fpga_accelerator_yolov3tiny\python_prj\yolov3tiny_quant.py", line 80, in quant_model_detect
x=quant_model[1].model[ii](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/issues/x)
File "D:\yolo_work\fpga_accelerator_yolov3tiny\python_prj\yolov3tiny_quant.py", line 97, in quant_model_evaluate_show
res=quant_model_detect(x,quant_model)
File "D:\yolo_work\fpga_accelerator_yolov3tiny\python_prj\yolov3tiny_quant.py", line 320, in
quant_model_evaluate_show(img_tensor,quant_model)
ValueError: Input shape must be (N, C, H, W)!
请问您有遇到这个问题吗

**Comment by huanggeli** [comment]
我没有调用过quant_model_evaluate_show，因此暂时没有遇到这个问题

**Comment by foooal** [comment]
> 我没有调用过quant_model_evaluate_show，因此暂时没有遇到这个问题

那请问您用的是这个python工程生成的量化权重吗？我在调用load_model_data（）函数的时候，出现这个
```
val: Scanning 'images.cache' images and labels... 0 found, 853 missing, 0 empty, 0 corrupted: 100%|
```
对加载权重又影响吗

**Comment by huanggeli** [comment]
没有影响，第一次加载就是有这个问题

**Comment by foooal** [comment]
还有两个问题想问下您？
一、generate_quant_model 和 load_quant_model 这个函数有什么区别吗？
二、我训练得到了权重文件，是不是只要按如下操做得到分割后的文件，存入SD卡就行：
```

float_model,dataloader_iter=load_model_data('face_mask.yaml','yolov3tiny_facemask.pt',416,False)
quant_model=load_quant_model('yolov3tiny_facemask.pt','yolov3tiny_facemask_quant.pth')
yolov3tiny_infer_para_gen(quant_model,32,'F',)
```

**Comment by huanggeli** [comment]
问题一，一个是生成量化模型，一个是加载模型。量化后的模型还需要将其参数提取出来适配加速器。
问题二，按操作得到分割后的bin文件，存入sd卡，并在zynq软件端修改正确的读取文件名即可
