### ISSUE TITLE
口罩识别不准确

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#12]
作者您好：
sd文件夹卡中的训量权重，导入到sd卡，插入板子后。对于戴口罩与不戴口罩，都被识别为戴口罩，偶尔会闪出incorrect和nomask。

**Comment by huanggeli** [comment]
是的，可能是训练模型的问题，建议尝试自行训练模型

**Comment by foooal** [comment]
想问下您在移植工程到7z035b工程中有没有修改网络呢。以方便确认是否原工程存在识别问题

**Comment by huanggeli** [comment]
没修改网络，后续我自己训练了其他场景验证但是没有开源，本项目使用的权重依旧是原工程的。
