### ISSUE TITLE
Platform is invalid. Please choose a valid platform.

### ISSUE THREAD

**Issue by luminita02** [huanggeli/yolov3tiny-ZYNQ7000#13]
我也遇到了相同的问题
![pic1](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/98135191/6d187081-8a76-4315-a034-b1e9ac5ec713)
![pic2](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/98135191/1220742b-7aa3-4168-a9c6-776156cef545)
也尝试过重新生成.xsa文件，创建一个新的工程，可能是不会，导入src中的文件重新build工程也会报错
![3](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/98135191/ce69ec29-b5c7-4e7a-8b4f-f68145c5d29f)
![5](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/98135191/b40cec25-2f17-45fb-bdc8-dc312630e4b9)
所以，在Platform Repositories上应该如何添加正确的平台呢，谢谢！

**Comment by huanggeli** [comment]
板卡型号？芯片型号？一般来说xil_printf这种库是platform提供的，跟源码无关，生成platform的过程检查一下。考虑用platform运行一个helloworld验证一下库在不在

**Comment by luminita02** [comment]
您好，有尝试过使用helloworld进行测试，在build project时结果是同样的报错信息，跟源码可能没有关系。跟板卡可能有什么关系吗，因为没有上板验证，使用的.xsa文件均是工程中提供的，谢谢

**Comment by huanggeli** [comment]
估计芯片型号不一致，自己重新build一个xsa吧，拿vivado把硬件的比特流文件重新编译再试试吧
