### ISSUE TITLE
vitis打开时报错怎么解决

### ISSUE THREAD

**Issue by size-chen520** [huanggeli/yolov3tiny-ZYNQ7000#14]
![2fa662ac2244bd1fd8e7dad12df1ea0](https://github.com/user-attachments/assets/099fa129-5d05-4d19-be4e-7f9da90a812e)
请问这种情况该怎么解决呢？

**Comment by huanggeli** [comment]
硬件重新编译一次，生成一个新的bitstream导进去吧
