### ISSUE TITLE
想问一下题主实现的推理时间是多少，我是47ms，感觉比原作者低不少呢

### ISSUE THREAD

**Issue by DragMou1204** [huanggeli/yolov3tiny-ZYNQ7000#15]

**Comment by huanggeli** [comment]
没有单独计算推理时间，包含完整的预处理和后处理大概是100MHZ时钟90ms左右

**Comment by DragMou1204** [comment]
奥奥好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月30日 22:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] 想问一下题主实现的推理时间是多少，我是47ms，感觉比原作者低不少呢 (Issue #15) |

没有单独计算推理时间，包含完整的预处理和后处理大概是100MHZ时钟90ms左右
