### ISSUE TITLE
想问下有论文成果或者说明文档吗

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#3]
想问下有论文成果或者说明文档吗

**Comment by huanggeli** [comment]
暂时没有，本项目以工程目标为导向，目的是在不支持Vitis-AI的zynq板卡上运行CNN，预处理和卷积使用RTL实现，后处理在PS端实现，如果需要创新性的研究方向建议Vitis-AI。由于近期没有建设说明文档的计划，如果有相关的工程问题欢迎在Issue区查询或提问。
