### ISSUE TITLE
vitis 编译报错 

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#4]
![微信图片_20240227102426](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/30284028/8981457c-555c-4c1a-915c-61793ef20967)
  
我在编译的时候遇到这个错误，请问有遇到过吗
vitis 版本：2019.1

**Comment by huanggeli** [comment]
我工程统一用的2021软件版本，如果是直接导入我的硬件platform进vitis，建议使用vitis2021版本。或是使用您自己的vivado2019重新编译一个硬件platform以适配vitis2019.

**Comment by foooal** [comment]
**抱歉，最近在19和21直接切换，写错了。我用的是2021.1，和你的一样。**
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/30284028/06a89f7d-5197-4b1f-806b-07cffc8377be)


**报错如下：**
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/30284028/9126c152-7a2d-467a-a52f-8037a4e5debf)


**这是我工程的Platform Repositories**
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/30284028/3670fc3b-2125-4136-a7e1-e90234a90d48)

**Comment by huanggeli** [comment]
在`VideoDetectionProject`文件夹下有一个名为`design_1_wrapper.xsa`的硬件文件，尝试用这个文件导入vitis建立一个自己的平台呢？然后使用自己创建的platform新建application，把`YOLOV3TINY-ZYNQ/VitisProject/detection_displayloop/src`目录下的源码复制过去编译也能运行

**Comment by foooal** [comment]
> 在`VideoDetectionProject`文件夹下有一个名为`design_1_wrapper.xsa`的硬件文件，尝试用这个文件导入vitis建立一个自己的平台呢？然后使用自己创建的platform新建application，把`YOLOV3TINY-ZYNQ/VitisProject/detection_displayloop/src`目录下的源码复制过去编译也能运行

我在vivado平台重新生成xsa，想请问下你的文件夹下有两个硬件平台，hardwareplatform.xsa和design_1_wrapper.xsa，这两个平台有什么区别呢

**Comment by foooal** [comment]
> 在`VideoDetectionProject`文件夹下有一个名为`design_1_wrapper.xsa`的硬件文件，尝试用这个文件导入vitis建立一个自己的平台呢？然后使用自己创建的platform新建application，把`YOLOV3TINY-ZYNQ/VitisProject/detection_displayloop/src`目录下的源码复制过去编译也能运行

我在vivado平台重新生成xsa，想请问下你的文件夹下有两个硬件平台，hardwareplatform.xsa和design_1_wrapper.xsa，这两个平台有什么区别呢？以及和vitis中的accel_hardware_platform有什么区别？

**Comment by huanggeli** [comment]
hardwareplatform.xsa和design_1_wrapper.xsa没有区别，是前后两次硬件编译的结果，使用任意一个均可。vitis中的accel_hardware_platform就是使用.xsa文件编译生成的platform，但是由于你使用过程中直接导入编译好的platform有报错，所以建议由原始xsa文件生成platform。

**Comment by foooal** [comment]
感谢
