### ISSUE TITLE
ff.h 头文件找不到

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#5]
**你好，vitis编译过程中有如下报错：**
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/30284028/3038c51f-8d48-44df-b880-b19f8413bdc9)
**检查ff.h，被包含在硬件平台中：**
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/30284028/51fc164d-2f77-449f-8746-f629d8c374d5)
请问有什么思路吗

**Comment by huanggeli** [comment]
ff是用于读取txt文件的库，这个报错原因是编译platform时没有编译这个库。在platform的设置中，将`xliff`库勾选上并重新编译即可。

**Comment by foooal** [comment]
感谢
