### ISSUE TITLE
更换自己的开发板后遇到的一些问题

### ISSUE THREAD

**Issue by qaq54600** [huanggeli/yolov3tiny-ZYNQ7000#6]
首先感谢您分享的工程！我的板卡是Zynq 7100（xc7z100ffg900-2）,经过测试能够正常运行OV5640的VDMA缓存以及HDMI显示实验。由于型号不同，我更换了您工程里vivado的ip以及相应的xdc约束文件，并且按照例程将5640和HDMI的ip进行移植，也更换了I2C配置的代码。目前出现以下问题，已将相关文件上传，还请博主不吝赐教

Q1：使用ILA抓取信号显示摄像头没有输入（行场信号也都为低电平），因此后面所有的AXIS数据流也都是为0，请问可能会是什么原因？（5640的输入时钟为25M）附BD工程的pdf等文件
[design_1.pdf](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/files/14419919/design_1.pdf)
![显示器结果](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/65234852/b4e336a2-a073-457a-ae01-8bc470865f7a)
![ILA抓取5640的输出](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/65234852/a9230c07-46e4-4db3-8936-76e87bc30dd3)

Q2：自己已经重新综合HLS的IP并导入工程，vivado综合完后仍然有提示重复调用但是文件不同，两个ip我都是分别存放在不同文件夹的，按理说不应该会冲突呀？

**Comment by qaq54600** [comment]
补充Q2的图片
![HLS的IP_warning](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/65234852/572cd553-4815-4335-bc8c-161c28d31249)

**Comment by huanggeli** [comment]
您好，关于Q1,查看了design之后发现你相机的IP的reset跟areset连接在一起了，考虑是不是相机的reset信号连反了。关于Q2我没有相关的处理经验，实在不行就从头开始移植，对照我项目的design及参数全部重构试试。目前已经有多个人提出类似Q2的移植问题了。如果有便捷的解决方案欢迎分享。
