### ISSUE TITLE
关于sd readme问题

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#7]
**Q1:** 
F -- Mask-Face Detection
H -- Helmet-Head Detection
人脸和头盔网络参数是作者自己训练的吗，以及训练相关配置。
**Q2:**
Switch boot mode to SD
press BTN1 to choose Helmet Detection or Mask-Face Detection
切换启动模式为SD，BTN1选择人脸或头盔检测，BTN1是什么按钮？

**Comment by huanggeli** [comment]
不是，神经网络的训练请参考https://github.com/adamgallas/fpga_accelerator_yolov3tiny，本项目仅对工程做了移植，由zynq mpsoc转移到zynq7000。

**Comment by foooal** [comment]
关于Q2，可以请教一下吗

**Comment by huanggeli** [comment]
BTN1是开发板调试时候设置的button，上传的工程文件里好像把这一部分删去了，要切换模型可以直接修改读取的权重文件。
