### ISSUE TITLE
”Load_pic();//加载图片“ 被注释问题

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#8]
想请问一下
 main函数中  “”Load_pic()”被注释掉，那函数中ifmInBuf这个变量就一直没有数据。那么vdma2好像就没有输入。

**Comment by huanggeli** [comment]
Load_pic()是测试sd卡单张图片用的，默认状态是往ifmInBuf存入视频流

**Comment by DragMou1204** [comment]
请问我想通过load_pic读取sd卡中图片进行检测，我应该怎么修改，我修改了这个函数的输入图片路径后显示的是摄像头视频，
我试着将ifmInBuf【1】与【2】与【3】都改成这个图片也不对，实际显示的依旧是摄像头视频
我关闭摄像头使能后，显示就黑屏了
![image](https://github.com/huanggeli/yolov3tiny-ZYNQ7000/assets/119485272/f8d3f59a-8343-474f-b15e-01f2f7e1956c)

**Comment by DragMou1204** [comment]
可能是我输入图片的二进制文件有问题，请问这个二进制的图片文件我该怎么实现

**Comment by huanggeli** [comment]
识别图片需要对图片进行二进制处理，推荐采用python的PIL和numpy库处理，需要仿照视频流的处理方式，对图片进行裁切以及降采样，将图片裁切至832*512，再进行二倍降采样至416*256，并将图片通道由三通道（RGB）拓展为八通道（补0实现），将所有RGB数据除2并向下取整（将0-255映射至0-127），最后存储为bin文件即可。注意检查转换后的数据格式，假设降采样后的416*256图片的第一行的前两个像素为 A,B，则图片数据的原始存储序列（RGB）是A_R,A_G,A_B,B_R,B_G,B_B，最终需要的二进制格式则是A_R/2,A_G/2,A_B/2,0,0,0,0,0,B_R/2,B_G/2,B_B/2,0,0,0,0,0







在 2024-04-28 19:27:29，"DragMou1204" ***@***.***> 写道：

可能是我输入图片的二进制文件有问题，请问这个二进制的图片文件我该怎么实现

**Comment by DragMou1204** [comment]
额，请问有现成代码吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月28日 20:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

识别图片需要对图片进行二进制处理，推荐采用python的PIL和numpy库处理，需要仿照视频流的处理方式，对图片进行裁切以及降采样，将图片裁切至832*512，再进行二倍降采样至416*256，并将图片通道由三通道（RGB）拓展为八通道（补0实现），将所有RGB数据除2并向下取整（将0-255映射至0-127），最后存储为bin文件即可。注意检查转换后的数据格式，假设降采样后的416*256图片的第一行的前两个像素为 A,B，则图片数据的原始存储序列（RGB）是A_R,A_G,A_B,B_R,B_G,B_B，最终需要的二进制格式则是A_R/2,A_G/2,A_B/2,0,0,0,0,0,B_R/2,B_G/2,B_B/2,0,0,0,0,0







在 2024-04-28 19:27:29，"DragMou1204" ***@***.***> 写道：

可能是我输入图片的二进制文件有问题，请问这个二进制的图片文件我该怎么实现

**Comment by yukizeng258** [comment]
@DragMou1204 请问waitAPdone的问题是怎么解决的，我也遇到了

**Comment by DragMou1204** [comment]
我是 sd 卡读取文件的时候读取错误，你可以检查一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 01:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

@DragMou1204 请问waitAPdone的问题是怎么解决的，我也遇到了

**Comment by yukizeng258** [comment]
我的好像不是欸，我看了读取的数据放置的地址，里面是有数据的。我是axi_lite配置了DMA，但是DMA没有输出。






1194859534
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanggeli/yolov3tiny-ZYNQ7000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月22日(星期三) 上午9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8)





 我是 sd 卡读取文件的时候读取错误，你可以检查一下
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年05月22日 01:56 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |
 
 @DragMou1204 请问waitAPdone的问题是怎么解决的，我也遇到了

**Comment by DragMou1204** [comment]
地址是 arm 端分配的，肯定会有数据，建议你检查一下读取的 ofm 或者我记得有一个参数是表示读取的实际数量的参数，建议检查一下是否为 0



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 09:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

我的好像不是欸，我看了读取的数据放置的地址，里面是有数据的。我是axi_lite配置了DMA，但是DMA没有输出。






1194859534
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huanggeli/yolov3tiny-ZYNQ7000" ***@***.***&gt;;
发送时间:&nbsp;2024年5月22日(星期三) 上午9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8)





我是 sd 卡读取文件的时候读取错误，你可以检查一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 日期 | 2024年05月22日 01:56 |
| 收件人 | ***@***.***&gt; |
| 抄送至 | ***@***.***&gt;***@***.***&gt; |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

@DragMou1204 请问waitAPdone的问题是怎么解决的，我也遇到了

**Comment by yukizeng258** [comment]
读取是有数据的
然后我读了DMA的控制寄存器也是正确写入传输地址和传输长度

但是我用ILA抓信号的话，MM2S的tvalid是一直没有拉高的


1194859534
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanggeli/yolov3tiny-ZYNQ7000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月22日(星期三) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8)





 地址是 arm 端分配的，肯定会有数据，建议你检查一下读取的 ofm 或者我记得有一个参数是表示读取的实际数量的参数，建议检查一下是否为 0
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年05月22日 09:20 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |
 
 我的好像不是欸，我看了读取的数据放置的地址，里面是有数据的。我是axi_lite配置了DMA，但是DMA没有输出。
 
 
 
 
 
 
 1194859534
 ***@***.***
 
 
 
 &amp;nbsp;
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "huanggeli/yolov3tiny-ZYNQ7000" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2024年5月22日(星期三) 上午9:10
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8)
 
 
 
 
 
 我是 sd 卡读取文件的时候读取错误，你可以检查一下
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&amp;gt; |
 | 日期 | 2024年05月22日 01:56 |
 | 收件人 | ***@***.***&amp;gt; |
 | 抄送至 | ***@***.***&amp;gt;***@***.***&amp;gt; |
 | 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |
 
 @DragMou1204 请问waitAPdone的问题是怎么解决的，我也遇到了

**Comment by DragMou1204** [comment]
load-para 函数中，输出一下 ofm-list 以及 wr-tot 是否为 0，如果为 0，说明读取数据有问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 09:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

读取是有数据的
然后我读了DMA的控制寄存器也是正确写入传输地址和传输长度

但是我用ILA抓信号的话，MM2S的tvalid是一直没有拉高的


1194859534
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huanggeli/yolov3tiny-ZYNQ7000" ***@***.***&gt;;
发送时间:&nbsp;2024年5月22日(星期三) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8)





地址是 arm 端分配的，肯定会有数据，建议你检查一下读取的 ofm 或者我记得有一个参数是表示读取的实际数量的参数，建议检查一下是否为 0



---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 日期 | 2024年05月22日 09:20 |
| 收件人 | ***@***.***&gt; |
| 抄送至 | ***@***.***&gt;***@***.***&gt; |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

我的好像不是欸，我看了读取的数据放置的地址，里面是有数据的。我是axi_lite配置了DMA，但是DMA没有输出。






1194859534
***@***.***



&amp;nbsp;




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: "huanggeli/yolov3tiny-ZYNQ7000" ***@***.***&amp;gt;;
发送时间:&amp;nbsp;2024年5月22日(星期三) 上午9:10
***@***.***&amp;gt;;
***@***.******@***.***&amp;gt;;
主题:&amp;nbsp;Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8)





我是 sd 卡读取文件的时候读取错误，你可以检查一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***&amp;gt; |
| 日期 | 2024年05月22日 01:56 |
| 收件人 | ***@***.***&amp;gt; |
| 抄送至 | ***@***.***&amp;gt;***@***.***&amp;gt; |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

@DragMou1204 请问waitAPdone的问题是怎么解决的，我也遇到了

**Comment by yukizeng258** [comment]
@DragMou1204 我看了wr_tot是不为0的

**Comment by DragMou1204** [comment]
我遇到的情况关于 dma 抓取数据部分跟你一样，我是读取的数据有问题，并没有读取到 sd 卡中的数据



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 19:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

@DragMou1204 我看了wr_tot是不为0的

**Comment by yukizeng258** [comment]
@DragMou1204 请问你是用的什么板卡呢

**Comment by DragMou1204** [comment]
zynq ultrascale➕的 zu5ev



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 19:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

@DragMou1204 请问你是用的什么板卡呢

**Comment by yukizeng258** [comment]
@DragMou1204 我的是黑金的zu4ev的，能分享一下您的设计吗

**Comment by DragMou1204** [comment]
最近会开源



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月22日 20:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huanggeli/yolov3tiny-ZYNQ7000] ”Load_pic();//加载图片“ 被注释问题 (Issue #8) |

@DragMou1204 我的是黑金的zu4ev的，能分享一下您的设计吗
