### ISSUE TITLE
输入特征图划分和并行处理的问题

### ISSUE THREAD

**Issue by foooal** [huanggeli/yolov3tiny-ZYNQ7000#9]
想问下输入特征图划分 Ci * H * W * 8这里，是什么意思呢。想了好久没想明白。
 
输入特征有40个通道，截断为5个8通道的意思吗？
如果是这样的话， H * W * 8 是什么意思呢

**Comment by huanggeli** [comment]
您是问软件还是硬件？

**Comment by huanggeli** [comment]
假设特征图有三个尺度height，width，channels（H,W,C），特征图有两种分块方式，一种是（H,W）长宽分块，另一种是（C）通道分块，HW分块的尺度取决于动态缓存行的长度L，分块尺度为L/(H*W)。通道分块的尺度则固定为8，意思是每次都固定传输8个通道的特征图。综上，一个H*W*C的特征图会被分块为h*w*8大小传输，其中h和w代表计算后的分块尺度。
